---
title: "session 4 notes"
author: "Tim Riffe"
date: "2024-07-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Get data (pasted in Doc)

```{r}
library(tidyverse)
library(readr)
library(janitor)
source("https://raw.githubusercontent.com/timriffe/BSSD2024Module2/master/02_lifetables.R")
B <- read_csv("https://raw.githubusercontent.com/timriffe/BSSD2024Module2/master/data/ES_B2014.csv") |> 
  mutate(sex = "total") |> 
  select(age, sex, births = total)

D<- read_csv("https://raw.githubusercontent.com/timriffe/BSSD2024Module2/master/data/ES_D2014.csv") |> 
     filter(year == 2014) |> 
  select(-open_interval) |> 
  pivot_longer(female:total, 
               names_to = "sex", 
               values_to = "deaths")

P <- read_csv("https://raw.githubusercontent.com/timriffe/BSSD2024Module2/master/data/ES_P.csv.gz") |> 
  clean_names() |> 
  select(-open_interval) |> 
  filter(year== 2014) |> 
  pivot_longer(female1:total2, 
               names_to = "sex", 
               values_to = "pop") |> 
  mutate(period = parse_number(sex),
         sex = gsub('[[:digit:]]+', '', sex)) |> 
  pivot_wider(names_from = period, values_from = pop, names_prefix="pop")

ES2014 <- 
  left_join(P, D, by = join_by(year,sex, age)) |> 
  left_join(B, by = join_by(sex, age))

LT <- 
  ES2014 |> 
  mutate(exposure = (pop1 + pop2) / 2,
         mx = deaths / exposure) |> 
  select(sex,age,mx) |> 
  group_by(sex) |> 
  group_modify(~LT_tidy(data = .x)) |> 
  ungroup()
```

Check out what we have:

```{r}
ES2014 |> 
  filter(sex == "total") |> 
  mutate(exposure = (pop1 + pop2) / 2) |> 
  summarize(E = sum(exposure),
            D = sum(deaths),
            B = sum(births, na.rm = TRUE),
            G = sum(pop2) - sum(pop1),
            P1 = sum(pop1),
            P2 = sum(pop2)) |> 
  mutate(CGR = G / E,
         CBR = B / E,
         CDR = D / E,
         CNMR = (P2 - (P1 + B - D)) / E,
         CNGR = CBR - CDR)
```

Let's build intuition on how growth rates can shape population age structure, using stable populations:

```{r}

r_values <- tibble(r = seq(-.03,.03,by=.005))
library(colorspace)
LT |> 
  filter(sex == "female") |> 
  select(age, Lx) |> 
  cross_join(r_values) |> 
  arrange(r, age) |> 
  group_by(r) |> 
  mutate(Cx = Lx * exp(-r*(age+.5)),
         Cx = Cx / sum(Cx)) |> 
  ggplot(aes(x = age, y = Cx, color = r, group = r)) +
  geom_line() +
  scale_color_binned_sequential() +
  theme_minimal()
```





